services:
  - type: web
    name: shiva-vexarts
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: ADMIN_EMAIL
        fromEnvVar: ADMIN_EMAIL
      - key: BLOB_READ_WRITE_TOKEN
        fromEnvVar: BLOB_READ_WRITE_TOKEN
      - key: VITE_BLOB_BASE_URL
        fromEnvVar: VITE_BLOB_BASE_URL
